apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-lws-operator-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-lws-operator-role
subjects:
  - kind: ServiceAccount
    name: openshift-lws-operator
    namespace: {{ .Values.namespace }}
