apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
  annotations:
    # Allow operator's Helm chart to adopt this ServiceAccount
    meta.helm.sh/release-name: default-istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
imagePullSecrets:
  - name: redhat-pull-secret
