apiVersion: v1
kind: ServiceAccount
metadata:
  name: lws-controller-manager
  namespace: openshift-lws-operator
  labels:
    app.kubernetes.io/managed-by: rhaii-on-xks
imagePullSecrets:
  - name: redhat-pull-secret
