apiVersion: v2
name: sail-operator
description: Red Hat Sail Operator (OSSM 3.x) for Kubernetes
type: application
version: 1.0.0
appVersion: "3.2.1"
keywords:
  - istio
  - service-mesh
  - gateway-api
  - sail-operator
maintainers:
  - name: Red Hat
sources:
  - https://github.com/istio-ecosystem/sail-operator
