{{- if and (eq .Values.bundle.source "redhat") .Values.pullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | b64enc }}
{{- end }}
