apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator3-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servicemesh-operator3-role
subjects:
  - kind: ServiceAccount
    name: servicemesh-operator3
    namespace: {{ .Values.namespace }}
