apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicemesh-operator3
  namespace: {{ .Values.namespace }}
{{- if eq .Values.bundle.source "redhat" }}
imagePullSecrets:
  - name: {{ .Values.pullSecret.name }}
{{- end }}
